import {
  red,
  pink,
  purple,
  deepPurple,
  indigo,
  blue,
  lightBlue,
  cyan,
  teal,
  green,
  lightGreen,
  lime,
  yellow,
  amber,
  orange,
  deepOrange,
  brown,
  grey,
  blueGrey
} from '@material-ui/core/colors'

export default {
  default: indigo,
  'Red': red,
  'Pink': pink,
  'Purple': purple,
  'Deep Purple': deepPurple,
  'Indigo': indigo,
  'Blue': blue,
  'Light Blue': lightBlue,
  'Cyan': cyan,
  'Teal': teal,
  'Green': green,
  'Light Green': lightGreen,
  'Lime': lime,
  'Yellow': yellow,
  'Amber': amber,
  'Orange': orange,
  'Deep Orange': deepOrange,
  'Brown': brown,
  'Grey': grey,
  'Blue Grey': blueGrey
}
